name: Continuous Deployment
on:
  workflow_run:
    workflows: [Continuous Integration]
    types: [completed]
    branches: [main]
jobs:
  on-success:
    name: Semantic Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/semantic-release.yaml
    secrets:
      GIT_TOKEN_BASIC: ${{ secrets.GIT_TOKEN_BASIC }}
