name: Deploy to S3 Bucket
on:
  workflow_call:
    inputs:
      endpointUrl:
        description: The endpoint URL of the S3 service. Change this when using S3 compatible services other than AWS, or when using account-specific FIPS endpoints.
        required: true
        type: string
        default: 'https://s3.us-east-1.amazonaws.com'
      bucketName:
        description: The name of the S3 bucket to which the files will be deployed.
        required: true
        type: string
      region:
        description: The primary region in which the S3 bucket exists.
        required: true
        type: string
        default: 'us-east-1'
      distPath:
        description: The path to the build output.
        required: true
        type: string
        default: './dist/'
      runDefaultBuild:
        description: Whether or not to run the build script from the project's package.json file.
        required: false
        type: boolean
        default: true
      buildArgs:
        description: Additional arguments to pass to `npm run build`.
        required: false
        type: string
        default: ''
      useGitLfs:
        description: Whether or not checkout should pull git-lfs files.
        required: false
        type: boolean
        default: false
      environment:
        description: The name of the environment being targeted.
        required: false
        type: string
        default: null
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      GIT_TOKEN_BASIC:
        required: false
jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GIT_TOKEN_BASIC || github.token }}
          lfs: ${{ inputs.useGitLfs }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install node dependencies
        run: npm ci
        shell: bash
      - name: Run default build
        if: inputs.runDefaultBuild == true
        run: npm run build -- ${{ inputs.buildArgs }}
        shell: bash
      - uses: actions/checkout@v4
        with:
          repository: fcgroup/actions
          path: ./.actions/
      - name: Install Node dependencies
        working-directory: ./.actions/scripts/deployment/deploy-files-to-s3/
        run: npm ci
        shell: bash
      - name: Deploy files to S3
        run: node ./.actions/scripts/deployment/deploy-files-to-s3/deploy-files-to-s3.js "${{ inputs.distPath }}" "${{ inputs.region }}" "${{ inputs.endpointUrl }}" "${{ inputs.bucketName }}"
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
