name: Nx Publish

on:
  workflow_call:
    inputs:
      git-tag:
        required: true
        type: string
      version:
        required: true
        type: string
      provenance:
        type: boolean
        default: false
    secrets:
      GIT_TOKEN_BASIC:
        required: true

jobs:
  npm_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release tag
        uses: actions/checkout@v7
        with:
          submodules: recursive
          ref: ${{ inputs.git-tag }}
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN_BASIC }}

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install latest NPM
        run: npm i -g npm@latest && npm --version

      - name: Install dependencies
        run: npm ci

      - name: Set Package Version
        run: npm version "${{ inputs.version }}" --no-git-tag-version

      - name: Publish with NPM
        run: npm publish --access public --provenance=${{ inputs.provenance }}
        env:
          # These are intentionally left blank to leverage the trusted publisher relationship between the GitHub Action and NPM.
          NODE_AUTH_TOKEN: ''
          NPM_CONFIG_USERCONFIG: ''
