name: Semantic Release
on:
  workflow_call:
    secrets:
      GIT_TOKEN_BASIC:
        required: true
      NPM_ACCESS_TOKEN:
        required: false
    inputs:
      environment:
        description: The environment that this job references.
        required: false
        type: string
        default: ''
    outputs:
      semver:
        description: The semantic version inferred from the commit history and assigned to the current commit hash.
        value: ${{ jobs.semantic-release.outputs.semver }}
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      semver: ${{ steps.get-semver.outputs.semver }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GIT_TOKEN_BASIC || github.token }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install node dependencies
        run: npm ci
        shell: bash
      - name: Set NPM access token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > .npmrc
        shell: bash
      - name: Run semantic-release
        run: npx semantic-release --dry-run false --ci false
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN_BASIC }}
      - uses: actions/checkout@v4
        with:
          repository: fcgroup/actions
          path: ./.actions/
      - id: get-semver
        name: Read generated semver
        run: ./.actions/scripts/versioning/get-semver.sh
        shell: bash
        env:
          CURRENT_COMMIT_HASH: ${{ github.sha }}
