name: Serverless Deploy
on:
  workflow_call:
    inputs:
      environment:
        description: The target deployment environment.
        required: true
        type: string
        default: production
    secrets:
      GIT_TOKEN_BASIC:
        required: true
      DYNAMIC_ENV_VARS:
        # Note: this is expected to be a JSON object string that is transcribed to the environment.
        required: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
          token: ${{ secrets.GIT_TOKEN_BASIC || github.token }}

      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          package-manager-cache: false

      - name: Install node dependencies
        run: npm ci || npm install
        shell: bash

      - name: Import Environment Variables
        run: echo '${{ secrets.DYNAMIC_ENV_VARS }}' | jq -r 'to_entries | map("export \(.key)=\(.value|@sh)") | .[]' >> .env
        shell: bash

      - name: Run deploy script
        run: |
          source .env
          npm run deploy
        shell: bash
