name: Terragrunt Apply
on:
  workflow_call:
    inputs:
      environment:
        description: The target deployment environment.
        required: true
        type: string
        default: production
      stacks:
        description: A JSON array of base stack directories.
        required: true
        type: string
      alwaysRun:
        description: Whether or not the job should be run regardless of other trigger conditions.
        required: false
        type: boolean
        default: false
      changeDetectionExpression:
        description: The regular expression pattern (passed to `grep -E`) that is used to match applicable files in a changeset.
        required: false
        type: string
        default: .*\.(hcl|json|yaml)$
      runsOn:
        description: The runner to use for the job.
        required: false
        type: string
        default: ubuntu-latest
      containerImage:
        description: The container image to use for the job. Currently only supports images in GHCR and will be prefixed with 'ghcr.io/'.
        required: false
        type: string
    secrets:
      GIT_TOKEN_BASIC:
        required: true
      CI_BOT_SSH_KEY:
        required: true
      TF_CLOUD_TOKEN:
        required: true
      DYNAMIC_ENV_VARS:
        # Note: this is expected to be a JSON object string that is transcribed to the environment.
        required: false

jobs:
  deployment_default:
    if: ${{ inputs.containerImage == '' }}
    runs-on: ${{ inputs.runsOn }}
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        stack: ${{ fromJson(inputs.stacks) }}
    steps:
      - name: Shared steps
        uses: fcgroup/actions/.github/actions/terragrunt-apply@main
        with:
          alwaysRun: ${{ inputs.alwaysRun }}
          changeDetectionExpression: ${{ inputs.changeDetectionExpression }}
        env:
          GIT_TOKEN_BASIC: ${{ secrets.GIT_TOKEN_BASIC }}
          CI_BOT_SSH_KEY: ${{ secrets.CI_BOT_SSH_KEY }}
          TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
          DYNAMIC_ENV_VARS: ${{ secrets.DYNAMIC_ENV_VARS }}

  deployment_containerized:
    if: ${{ inputs.containerImage != '' }}
    runs-on: ${{ inputs.runsOn }}
    container:
      image: 'ghcr.io/${{ inputs.containerImage }}'
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        stack: ${{ fromJson(inputs.stacks) }}
    steps:
      - name: Shared steps
        uses: fcgroup/actions/.github/actions/terragrunt-apply@main
        with:
          alwaysRun: ${{ inputs.alwaysRun }}
          changeDetectionExpression: ${{ inputs.changeDetectionExpression }}
        env:
          GIT_TOKEN_BASIC: ${{ secrets.GIT_TOKEN_BASIC }}
          CI_BOT_SSH_KEY: ${{ secrets.CI_BOT_SSH_KEY }}
          TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
          DYNAMIC_ENV_VARS: ${{ secrets.DYNAMIC_ENV_VARS }}
